### ISSUE TITLE
Failed to list versions for com.commonsware.cwac:security

### ISSUE THREAD

**Issue by jiaoyang28** [commonsguy/cwac-security#25]
Hi,

We were using the com.commonsware.cwac:security, and the code built successfully until Dec. 7th 2021. 

Now, when we try to build, we got the following exception:
`> Failed to list versions for com.commonsware.cwac:security.
      > Unable to load Maven meta-data from http://dl.bintray.com/amulyakhare/maven/com/commonsware/cwac/security/maven-metadata.xml.
         > Could not get resource 'http://dl.bintray.com/amulyakhare/maven/com/commonsware/cwac/security/maven-metadata.xml'.
            > Could not GET 'http://dl.bintray.com/amulyakhare/maven/com/commonsware/cwac/security/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
`
Seems the package is not accessible anymore. 

May I ask you to have a check on it? If it get relocated, may I ask what is the new path?

Thank you very much.

**Comment by commonsguy** [comment]
That is not my artifact. You have been using somebody else's artifact, using the same Maven coordinates but in somebody else's Maven repository.

Your primary option is to either fork this repo or otherwise copy the code. As is noted on the project home page, this project is discontinued, and this repo will be made private very soon.

Otherwise, please follow the instructions from the project home page, where it shows the repository where my artifacts are published:

```gradle
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}
```
